<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1527393363193" stop="1527393363240">
  <name>test01</name>
  <labels/>
  <test-cases>
    <test-case start="1527393363193" status="passed" stop="1527393363208">
      <name>Test_01.test_abc[1]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="4064-MainThread"/>
        <label name="host" value="LAPTOP-L1I9BI9H"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1527393363208" status="failed" stop="1527393363240">
      <name>Test_01.test_abc[2]</name>
      <failure>
        <message>AssertionError: assert 2 != 2</message>
        <stack-trace>self = &lt;test01.Test_01 object at 0x000001EACD3B0710&gt;, a = 2

    @pytest.mark.parametrize('a',[1,2,3])
    def test_abc(self,a):
&gt;       assert  a !=2
E       assert 2 != 2

scripts\test01.py:8: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="4064-MainThread"/>
        <label name="host" value="LAPTOP-L1I9BI9H"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1527393363240" status="passed" stop="1527393363240">
      <name>Test_01.test_abc[3]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="4064-MainThread"/>
        <label name="host" value="LAPTOP-L1I9BI9H"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
